planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ['GridBased']
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'

global_costmap:
  global_costmap:
    ros__parameters:
      # Whether to send full costmap every update, rather than updates. (default: false)
      always_send_full_costmap: False

      # Reference frame. (default: map)
      global_frame: map

      # Frequency to publish costmap to topic. (default 1.0)
      publish_frequency: 10.0

      # Height of costmap (m). (default: 5)
      width: 8

      # Width of costmap (m). (default: 5)
      height: 8

      # Resolution of 1 pixel of the costmap, in meters. (default: 0.1)
      resolution: 0.05

      # Robot base frame. (default: base_link)
      robot_base_frame: agent_1

      # Robot radius to use, if footprint coordinates not provided. (default: 0.1)
      robot_radius: 0.2

      # Whether costmap should roll with robot base frame. (default: False)
      rolling_window: True

      # Costmap update frequency. (default 5.0)
      update_frequency: 5.0

      # Whether when combining costmaps to use the maximum cost or override. (default: False)
      use_maximum: False

      # List of mapped plugin names for parameter namespaces and names. Note: Each plugin namespace
      # defined in this list needs to have a plugin parameter defining the type of plugin to be
      # loaded in the namespace.
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        # https://navigation.ros.org/configuration/packages/costmap-plugins/static.html

        # QoS settings for map topic. (default: True)
        map_subscribe_transient_local: True

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        # https://navigation.ros.org/configuration/packages/costmap-plugins/inflation.html

        # Whether the inflation_layer plugin is enabled. (default: True)
        enabled: True

        # Radius to inflate costmap around lethal obstacles. (default: 0.55)
        inflation_radius: 0.55

        # Exponential decay factor across inflation radius. (default: 10.0)
        cost_scaling_factor: 10.0

        # Whether to inflate unknown cells as if lethal. (default: False)
        inflate_unknown: False

        # Whether to inflate unknown cells. (default: False)
        inflate_around_unknown: False

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "turtlebot3_world.yaml"
    save_map_timeout: 5.0